/* ====== TrustGen — Story Mode Overlay ======
 * HTML overlay rendered on top of the 3D canvas during
 * story playback. Shows:
 *   - Title card (fade in/out during first shot)
 *   - Narration subtitles (lower-third captions)
 *   - Shot counter
 *   - Playback timeline bar
 */

import { useStoryStore } from '../stores/storyStore'

export function StoryOverlay() {
    const playing = useStoryStore(s => s.playback.playing)
    const currentTime = useStoryStore(s => s.playback.currentTime)
    const totalDuration = useStoryStore(s => s.playback.totalDuration)
    const activeShotIndex = useStoryStore(s => s.playback.activeShotIndex)
    const shots = useStoryStore(s => s.shots)
    const title = useStoryStore(s => s.title)
    const timeline = useStoryStore(s => s.timeline)
    const status = useStoryStore(s => s.status)

    // Only render during playback
    if (!playing) return null
    if (status !== 'ready' && status !== 'done') return null
    if (!shots.length) return null

    const activeShot = shots[activeShotIndex]
    const isTitle = activeShot?.name?.includes('Title')
    const isCredits = activeShot?.name?.includes('Credits')
    const progress = totalDuration > 0
        ? (currentTime / totalDuration) * 100
        : 0

    // Get narration text for the current scene
    // Offset by 1 to skip title card shot
    const sceneIndex = Math.max(0, activeShotIndex - 1)
    const sceneText = timeline?.scenes?.[sceneIndex]?.text || ''

    return (
        <div className="story-overlay" style={{ opacity: 1 }}>
            {/* Title Card */}
            {isTitle && (
                <div className="story-overlay-title">
                    <div className="story-overlay-title-text">{title}</div>
                    <div className="story-overlay-title-sub">A TrustGen Documentary</div>
                </div>
            )}

            {/* Credits */}
            {isCredits && (
                <div className="story-overlay-credits">
                    <div className="story-overlay-credits-line">Generated by TrustGen 3D</div>
                    <div className="story-overlay-credits-line dim">Story Mode &bull; AI Director &bull; Sequencer</div>
                    <div className="story-overlay-credits-line dim">DarkWave Studios</div>
                </div>
            )}

            {/* Narration Subtitles (lower third) */}
            {!isTitle && !isCredits && sceneText && (
                <div className="story-overlay-caption">
                    <span className="story-overlay-caption-text">{sceneText}</span>
                </div>
            )}

            {/* Shot Counter (top-right) */}
            <div className="story-overlay-counter">
                Scene {activeShotIndex + 1} / {shots.length}
            </div>

            {/* Title Watermark (top-left) */}
            {!isTitle && (
                <div className="story-overlay-watermark">
                    {title}
                </div>
            )}

            {/* Timeline bar (bottom) */}
            <div className="story-overlay-timeline">
                <div
                    className="story-overlay-timeline-fill"
                    style={{ width: `${progress}%` }}
                />
            </div>
        </div>
    )
}
